name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js enviroment
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        with:
          node-version: 10.x

      # Instalar depenências do YARN
      - name: Install depenendencies
        run: yarn

      # Executar Build
      - name: Install depenendencies
        run: yarn build

      # Copiar arquivos para Digital Ocean
      - name: Copy code to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules'
          target: '~/app/auth-manage'

      # Executar Yarn na Digital Ocean
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/auth-manage
            yarn
            pm2 restart auth-manage
